<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'SanAuth\Module'                           => __DIR__ . '/Module.php',
    'SanAuth\Controller\AuthController'        => __DIR__ . '/src/SanAuth/Controller/AuthController.php',
    'Application\Controller\SuccessController' => __DIR__ . '/src/SanAuth/Controller/SuccessController.php',
    'SanAuth\Model\User'                       => __DIR__ . '/src/SanAuth/Model/User.php',
);